### ISSUE TITLE
appendToBody doesn't show up in Pursuit

### ISSUE THREAD

**Issue by seagreen** [parsonsmatt/purescript-routing-example#1]
It looks like Halogen.Util doesn't have it anymore: https://pursuit.purescript.org/packages/purescript-halogen/0.8.0/docs/Halogen.Util

**Comment by parsonsmatt** [comment]
Thanks for checking it out! Currently the branch/blog post are for Halogen 0.5. I'd need to do a full upgrade in order to get that working.

**Comment by seagreen** [comment]
Ah, that makes sense.

**Comment by sportanova** [comment]
@seagreen upgraded to halogen 0.8.0 and router 0.4.0 https://github.com/parsonsmatt/purescript-routing-example/pull/2

**Comment by parsonsmatt** [comment]
Thanks to @sportanova for updating it :smile:

**Comment by sportanova** [comment]
@parsonsmatt thanks for this example - would have been fucked without it!
