### ISSUE TITLE
Not working with purescript 14.2, routing 10.0.1, halogen 6.1.2

### ISSUE THREAD

**Issue by KaneRoot** [parsonsmatt/purescript-routing-example#8]
Hello,

I like your application. To me it's useful to have that to understand how everything works and not just some parts of the routing module API, but it is currently not working.

Can you fix your repository to be working with current versions of everything?

Thanks!

**Comment by parsonsmatt** [comment]
I'd be happy to accept a PR bringing it up to date, but I don't currently work with PureScript and haven't touched Halogen since (checks repo) 6 years ago.

**Comment by KaneRoot** [comment]
Okay, thanks for your quick response.
